apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  selector:
    matchLabels:
      name: hello-kubernetes
  template:
    metadata:
      labels:
        name: hello-kubernetes
    spec:
      containers:
      - name: app
        image: megatestacr.azurecr.io/webnginx:v21
        # image: megatestacr.azurecr.io/webnginx:#{Build.BuildId}#
        
        ports:
          - containerPort: 80